/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;

import java.awt.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Pooja
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        this.setLocationRelativeTo(null);
        welcome.setText("<html>" + "WELCOME TO:" + "</html>");
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("info.png")));

        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(info.getWidth(), info.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);

        info.setIcon(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dna1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        dna2 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        s3 = new javax.swing.JButton();
        s1 = new javax.swing.JButton();
        welcome2 = new javax.swing.JLabel();
        s2 = new javax.swing.JButton();
        welcome1 = new javax.swing.JLabel();
        s4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setMaximumSize(new java.awt.Dimension(21000, 1000));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dna1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/dna.gif"))); // NOI18N
        jPanel1.add(dna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.setToolTipText("EXIT THE APPLICATION");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 650, 120, 40));

        dna2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/dna.gif"))); // NOI18N
        jPanel1.add(dna2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        welcome.setFont(new java.awt.Font("Lucida Handwriting", 3, 48)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("WELCOME TO:");
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 340, 140));

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/info.png"))); // NOI18N
        info.setText("jLabel3");
        info.setToolTipText("CLICK HERE FOR MORE INFORMATION");
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
        });
        jPanel1.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 40, 40));

        s3.setBackground(new java.awt.Color(0, 0, 0));
        s3.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        s3.setForeground(new java.awt.Color(0, 255, 0));
        s3.setText("MUTATION CHECKER");
        s3.setToolTipText("GO TO MUTATION CHECK");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 330, 40));

        s1.setBackground(new java.awt.Color(0, 0, 0));
        s1.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        s1.setForeground(new java.awt.Color(51, 255, 0));
        s1.setText("SEQUENCE VALIDATOR");
        s1.setToolTipText("GO TO SEQUENCE VALIDATOR");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 330, 40));

        welcome2.setFont(new java.awt.Font("Lucida Handwriting", 3, 48)); // NOI18N
        welcome2.setForeground(new java.awt.Color(255, 0, 0));
        welcome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/DNA detective.gif"))); // NOI18N
        welcome2.setText(" ");
        jPanel1.add(welcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 490, 260));

        s2.setBackground(new java.awt.Color(0, 0, 0));
        s2.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        s2.setForeground(new java.awt.Color(51, 255, 0));
        s2.setText("SEQUENCE SIMILARITY");
        s2.setToolTipText("GO TO SEQUENCE SIMILARITY");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 330, 40));

        welcome1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        welcome1.setForeground(new java.awt.Color(255, 255, 255));
        welcome1.setText("Choose An Option:");
        jPanel1.add(welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 360, 60));

        s4.setBackground(new java.awt.Color(0, 0, 0));
        s4.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        s4.setForeground(new java.awt.Color(0, 255, 0));
        s4.setText("PROTEIN SYNTHESIS");
        s4.setToolTipText("GO TO PROTEIN SYNTHESIS");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 330, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked

        Info info = new Info();
        info.show();
        dispose();

    }//GEN-LAST:event_infoMouseClicked

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed

        Mutation m = new Mutation();
        m.show();
        dispose();
    }//GEN-LAST:event_s3ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed

        SequenceValidator sv = new SequenceValidator();
        sv.show();
        dispose();

    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed

        SeqSimInterface ss = new SeqSimInterface();
        ss.show();
        dispose();
    }//GEN-LAST:event_s2ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed

        ProteinSynthesis ps = new ProteinSynthesis();
        ps.show();
        dispose();
    }//GEN-LAST:event_s4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dna1;
    private javax.swing.JLabel dna2;
    private javax.swing.JButton exit;
    private javax.swing.JLabel info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcome1;
    private javax.swing.JLabel welcome2;
    // End of variables declaration//GEN-END:variables
}
